language: php

php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.4snapshot'

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - SYMFONY_VERSION="^3.4"
  - COMPOSER_FLAGS=""

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi;

install:
  - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/simple-phpunit

notifications:
  email:
    - info@endroid.nl
