services:
    Endroid\CmSms\Client: ~
    Endroid\CmSmsBundle\Controller\DashboardController: ~
    Endroid\CmSmsBundle\Controller\MessageListController:
        - '@Endroid\CmSmsBundle\Repository\MessageRepository'
    Endroid\CmSmsBundle\Controller\MessageSendController:
        - '@Endroid\CmSmsBundle\Repository\MessageRepository'
    Endroid\CmSmsBundle\Controller\StatusUpdateController:
        - '@Endroid\CmSmsBundle\Repository\MessageRepository'
    Endroid\CmSmsBundle\Repository\MessageRepository:
        factory: ['@Doctrine\ORM\EntityManagerInterface', 'getRepository']
        arguments:
            - 'Endroid\CmSmsBundle\Entity\Message'