services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Endroid\CmSms\Client: ~

    Endroid\CmSmsBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Endroid\CmSmsBundle\Repository\MessageRepository:
        factory: ['@Doctrine\ORM\EntityManagerInterface', 'getRepository']
        arguments: ['Endroid\CmSmsBundle\Entity\Message']
