parameters:
    env(CM_SMS_DISABLE_DELIVERY): ~
    env(CM_SMS_PRODUCT_TOKEN): ~

endroid_cm_sms:
    disable_delivery: '%env(bool:CM_SMS_DISABLE_DELIVERY)%'
    product_token: '%env(string:CM_SMS_PRODUCT_TOKEN)%'
    defaults:
        sender: 'Endroid'
        unicode: 'auto'
        minimum_number_of_message_parts: 1
        maximum_number_of_message_parts: 3
