parameters:
    env(CM_SMS_PRODUCT_TOKEN): ''

endroid_cm_sms:
    product_token: '%env(CM_SMS_PRODUCT_TOKEN)%'
    defaults:
        sender: 'Endroid'
        unicode: 'auto'
        minimum_number_of_message_parts: 1
        maximum_number_of_message_parts: 3
